### ISSUE TITLE
Are the themes missing?

### ISSUE THREAD

**Issue by alexsavio** [Neurita/neurita.github.io#1]
Hola,
Cuando hago `./developer_server.sh start` en el branch `dev` y enciendo el firefox, aparece el contenido, pero parece que falta el tema.
Estoy hablando con la designer para hacer un tema (te pongo en copia), pero me imagino que necesitará un tema base del que partir.

**Comment by ljsalvatierra** [comment]
Solucionado, no sé por qué, pero no se había subido el tema, creo que era algo relacionado con 'submódulos'.

**Comment by alexsavio** [comment]
Sí, vi el submodulo. Faltaba el path de submodulo. Se puede activar el
submodulo, pero habria que indicar en el README cómo clonar el repositorio
con el 'recursive'.

Alexandre Manhães Savio [image: cid:part1.05060801.02000507@gmail.com]
http://scholar.google.es/citations?user=h_jN_q4AAAAJ&hl=en
PhD, Medical Imaging, Machine Learning
ENGINE Project http://engine.pwr.wroc.pl Wrocław University of Technology
home http://alexsavio.github.io/ | email: alexsavio@gmail.com

2015-08-26 15:21 GMT+02:00 Luis J. Salvatierra notifications@github.com:
